//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoProveedor
    {
        public int CodigoProvee { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Cargo { get; set; }
        public string IdProveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
