//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoProveedor
    {
        public int CodigoProvee { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Cargo { get; set; }
        public string IdProveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
