//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaCompra
    {
        public int Codigo { get; set; }
        public int NumeroFactura { get; set; }
        public int CodigoEquipo { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual FacturaCompra FacturaCompra { get; set; }
    }
}
