//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoProgramacion
    {
        public int Codigo { get; set; }
        public int CodigoEquipo { get; set; }
        public int IdProgramacion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Programacion Programacion { get; set; }
    }
}
