//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoProgramacion
    {
        public int Codigo { get; set; }
        public int CodigoEquipo { get; set; }
        public int IdProgramacion { get; set; }
        public int Cantidad { get; set; }
        [JsonIgnore]
        public virtual Equipo Equipo { get; set; }
        [JsonIgnore]
        public virtual Programacion Programacion { get; set; }
    }
}
