//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaCompra()
        {
            this.DetalleFacturaCompras = new HashSet<DetalleFacturaCompra>();
        }
    
        public int NumeroFactura { get; set; }
        public int CodigoEmpleCargo { get; set; }
        public string IdProveedor { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaCompra> DetalleFacturaCompras { get; set; }
        public virtual EmpleadoCargo EmpleadoCargo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
