//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaCompra()
        {
            this.DetalleFacturaCompras = new HashSet<DetalleFacturaCompra>();
        }
    
        public int NumeroFactura { get; set; }
        public int CodigoEmpleCargo { get; set; }
        public string IdProveedor { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaCompra> DetalleFacturaCompras { get; set; }
        public virtual EmpleadoCargo EmpleadoCargo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
