//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesEquipo
    {
        public int IdImagen { get; set; }
        public string NombreImagen { get; set; }
        public int CodigoEquipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
