//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesEquipo
    {
        public int IdImagen { get; set; }
        public string NombreImagen { get; set; }
        public int CodigoEquipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
